version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: "chat-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null 
  graphql:
    build: 
      context : ./
      dockerfile: backend-dev
    container_name: "chat-graphql"
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7071:4000
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=chat
      - HTTPS=false
      - JWT_SECRET_TOKEN=SuperSecureButYouShouldChangeMe
      - ALLOW_CORS_FRONTEND=http://localhost:7070
  front:
    build: 
      context: ./
      dockerfile: frontend-dev
    container_name: "chat-front"
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7070:3000
    depends_on:
      - graphql
    environment:
      - REACT_APP_BACKEND=localhost:7071
      - REACT_APP_PROTOCOL=http

networks:
  default:
    external:
      name: root_default