version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: "chat-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null 
  graphql:
    build: 
      context : ./
      dockerfile: backend-prod
    container_name: "chat-graphql"
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=chat
      - JWT_SECRET_TOKEN=SuperSecureButYouShouldChangeMe
      - "ALLOW_CORS_FRONTEND=https://front.arthurdev.duckdns.org"
      - VIRTUAL_HOST=graphql.arthurdev.duckdns.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=graphql.arthurdev.duckdns.org
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
      - SENDGRID_API_KEY=SG.SENDGRIDKEY.YouShouldAddYoursForEmailToWork
      - SENDGRID_FROM_EMAIL=automailer@your.domain.com
  front:
    build: 
      context: ./
      dockerfile: frontend-prod
    container_name: "chat-front"
    depends_on:
      - graphql
    environment:
      - VIRTUAL_HOST=front.arthurdev.duckdns.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=front.arthurdev.duckdns.org
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com

networks:
  default:
    external:
      name: arthur_default